auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path('createListing', views.createListing, name='createListing'),
   path("categoryList/<str:category_id>", views.categoryList, name='categoryList'),
   path("addWatchlist/<int:auction_id>", views.addWatchlist, name="addWatchlist"),
   path("watchlist", views.watchlist, name="watchlist"),
   path("remove_watchlist/<int:auction_id>", views.remove_watchlist, name="remove_watchlist"),
   path("indexItem/<int:auction_id>", views.indexItem, name="indexItem"),
   path('PostImage/<int:auction_id>', views.PostImage, name="PostImage")
   
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from PIL import Image
from PIL.Image import core as _imaging
from django.conf import settings
from django.conf.urls.static import static


class User(AbstractUser):
    id = models.AutoField(primary_key=True)
    pass

class Category(models.Model):
    id = models.AutoField(primary_key=True)
    category = models.CharField(max_length=25)


    def __str__(self):
        return f"{self.category}"

class Auction(models.Model):
    id = models.AutoField(primary_key=True)

    STATUS = (
        ('Active', 'Active'),
        ('Closed', 'Closed'),
        ('Sold', 'Sold'),
    )
    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    price = models.FloatField()
    description = models.TextField()
    active = models.CharField(max_length=25, choices=STATUS)
    selectcategory = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="media", blank=True)
    date = models.DateTimeField(auto_now_add=True)
    

    def __str__(self):
        return f"{self.seller}, {self.title}, {self.description}, {self.active}, {self.price}, {self.date},{self.active}, {self.image}"


class PostImage(models.Model):
    id = models.AutoField(primary_key=True)
    auction = models.ForeignKey(Auction, default=None, on_delete=models.CASCADE, related_name="postImage")
    images = models.ImageField(upload_to="media/", blank=True)

    def __str__(self):
        return self.auction.title


class Bid(models.Model):
    id = models.AutoField(primary_key=True)
    buyer = models.ForeignKey(User, on_delete=models.CASCADE, related_name="buyer_name")
    product_id = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name="product_bids")
    product_price = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.buyer}, {self.product_price}, {self.date}"

class Comment(models.Model):
    id = models.AutoField(primary_key=True)
    product_id = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name="product_comments")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user")
    date = models.DateTimeField(auto_now_add=True)
    comment = models.TextField()

    def __str__(self):
        return f"{self.user},  {self.comment}, {self.product_id}"

class Watchlist(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_watchlist")
    product_id = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name="product_watchlist")

    def __str__(self):
        return f"{self.user}, {self.product_id}"

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from .models import *
from django.core.files.storage import FileSystemStorage
import os, os.path
from django.contrib import messages

def index(request):
    #Get all objects in both models and render them.
   
    return render(request, "auctions/index.html",{
        "auctions": Auction.objects.all(),
        "photos": PostImage.objects.all(),
        "categories": Category.objects.all()
    })

def indexItem(request, auction_id):
    product = Auction.objects.get(pk = auction_id)
    postImage = PostImage.objects.filter(auction=auction_id)
    return render(request, "auctions/index_view.html",{
        'product': product,
        'postImage': postImage,
        "categories": Category.objects.all()
    })

def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            #logging.info(f'{username} logged in.')
            return HttpResponseRedirect(reverse("index"))
        else:
            #logging.warning(f'{username} logged in Invalid username and/or password..')
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:

            #logging.warning(f'{username}-{email}typed in an incorrect password!')
            
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
            #logging.info(f'{username}-{email} just signed up!')
        except IntegrityError:
            #logging.warning(f'{username} already taken')
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")

def createListing(request):
    if request.method == "POST":
        product = Auction()
        photos = PostImage()
        category = Category.objects.get(id=int(request.POST["category"]))
        
        product.title = request.POST["title"]
        product.seller = request.user
        product.description= request.POST["description"]
        product.active = request.POST["active"]
        product.price = request.POST["price"]
        product.image = request.FILES['image']
        product.selectcategory = category
        product.save()

        # Return the last updated id from product and update it to the PostImage model.
        photos.auction = Auction.objects.latest('id')

        #Get all the images uploaded to the path.
        images = request.FILES.getlist('images')
        
        #Loop through all the images uploaded and post each.
        if images:
            for image in images:
                photos = PostImage.objects.create(images=image, auction=photos.auction)
        photos.save()
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/create.html",{
            "auctions":Auction.objects.all(),
            "categories": Category.objects.all(),
            "photos": PostImage.objects.all()
        })


def categoryList(request,category_id):
    products = Auction.objects.filter(selectcategory=category_id)
    if len(products) >= 1:
        return render(request, "auctions/category.html",{
        "auctions":Auction.objects.all(),
        "products": products,
        "categories": Category.objects.all()
    })

    else: 
        return redirect("index")

def watchlist(request):
    product_watchlist = Watchlist.objects.all().select_related('product_id')
    if product_watchlist:
        return render(request, "auctions/watchlist.html", {
            'product_watchlist': product_watchlist,
            "categories": Category.objects.all()
        })
    else:
        return render(request, "auctions/watchlist.html", {
            "message": "Empty",
            "categories": Category.objects.all()
        })

def addWatchlist(request, auction_id):
    query = Auction.objects.get(pk = auction_id)
    Watchlist.objects.create(user = request.user, product_id = query)
    return redirect(watchlist)
   
def remove_watchlist(request, auction_id):
    query = Watchlist.objects.filter(user = request.user, product_id = auction_id)
    print(query)
    if query:

        query.delete()

    return HttpResponseRedirect(reverse("watchlist"))



          


        

auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %}

{%block body%}
    
<div class="container margin-bottom">
    {% for product in products%}
        <div class="row featurette">
            <div class="col-md-7">
                <li style="text-align: right;">{{product.active}}</li>
                <div >
                    <h2>{{product.title}} </h2><br>
                </div>
                
                <div>
                        Description
                    <li>{{product.description}}</li>
                </div>
                <div>
                    Seller
                    <li>{{product.seller}}</li>
                </div>

            </div>
            <div class="col-md-5">
                <img src="{{product.image.url}}" alt="" width="500" height="500"> 
            </div>
            <div>
                <a href="{% url 'addWatchlist' auction_id=product.id %}" class="btn btn-light col-2 pr-2">Add to Watchlist</a>
            </div>
        </div>

        <hr class="featurette-divider">

    {%endfor%}

</div>

{%endblock%}

auctions/templates/auctions/category_list.html
{% extends "auctions/layout.html" %}

{%block body%}

<br>

{% if message  %}

<div class="alert alert-danger">

    {{message}}

</div>

{%endif%}

{% for product in products%}

<div>       
    <h3> {{product.title}} </h3><br>
    <img src="{{product.image.url}}" alt="" width="300"> 
</div>
<div>
    <li>{{product.date}}</li>
</div>
<div>
    Description
   <li>{{product.description}}</li> 
</div>
<div>Seller
    <li>{{product.seller}}</li>
</div>

<div>Category
    <li>{{product.selectcategory}}</li>
</div>
<div>Status
    <li>{{product.active}}</li>
</div>
{%endfor%}
{%endblock%}

auctions/templates/auctions/create.html
{% extends "auctions/layout.html" %}



{% block body %}
{% include "auctions/slider.html" %}
<hr>
{% if message %}
<div>{{ message }}</div>
{% endif %}
<div class="conTainer">

    <form action="{% url 'createListing' %}" method="POST" enctype=multipart/form-data>
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="title" placeholder="Titles">
        </div>
        <div class="form-group">
            <textarea class="form-control" name="description" rows="4" placeholder="Descriptions"></textarea>
        </div>
        <div class="form-group">
            <select class="form-select" aria-label="Default select example" name="categorys">
                {% for category in categories %}
                <option value="{{category.id}}">{{category.category}}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <input class="form-control" type="text" name="price" placeholder="price">
        </div>
        <div class="form-group">
            <select class="form-select" aria-label="Default select example" name="active" required=""
                id="id_active">

                <option selected>Active</option>

                <option value="Active">Active</option>

                <option value="Closed">Closed</option>

                <option value="Sold">Sold</option>

            </select>
        </div>
        <div class="form-group">
            <input class="form-control" type="file" name="image" placeholder="Image" multiple>
            <label>Add more:</label>
            <input class="form-control" type="file" name="images" placeholder="Add more" multiple>
        </div>
        <input class="btn btn-primary" type="submit" value="Create">
    </form>


</div>
<!-- End Jumbotron -->
{% endblock %}

auctions/templates/auctions/index-view-swiper.html
{% load static %}
<head>

    <link rel="stylesheet" href="{% static 'auctions/swiper-bundle.min.css' %}">
</head>
<body>

    <!-- Swiper -->
    <div class="swiper-container">
        <div class="swiper-wrapper">
            {% for post in postImage%}
            <div class="swiper-slide"><img src="{{post.images.url}}" alt="" width="600" height="500"></div>
            {%endfor%}
        </div>
        <!-- Add Pagination -->
        <div class="swiper-pagination"></div>
        <!-- Add Arrows -->
        <div class="swiper-button-next"></div>
        <div class="swiper-button-prev"></div>
    </div>

    <!-- Swiper JS -->
    <script src="{% static '/auctions/scripts/swiper-bundle.js' %}"></script>

    <!-- Initialize Swiper -->
    <script>
        var swiper = new Swiper('.swiper-container', {
            pagination: {
                el: '.swiper-pagination',
                type: 'fraction',
            },
            navigation: {
                nextEl: '.swiper-button-next',
                prevEl: '.swiper-button-prev',
            },
        });
    </script>
</body>

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}

{% include "auctions/slider.html" %}

    
        <div class="container mb-4">
            <div class="index-bottom">
                <div class="row">
                
                    {% for auction in auctions %}
                
                    {%if auction.active == "Active" %}
                
                    <div class="col-lg-3 col-sm-6 pr-2 mb-4">
                
                        <div class="listing">
                
                            <h4 class="pd-2 pr-2 pl-2 pt-2"> {{auction.title}} </h4>
                
                            <div class="center-align">
                
                                <img src="{{auction.image.url}}" alt="" width="300" height="250">
                
                            </div>
                
                            <div class="row">
                
                                <p class="col-6 ml-2">${{auction.price}}</p>
                
                                <a class="btn btn-light col-5 pr-2" href="{% url 'indexItem' auction_id=auction.id%}">View detaills
                                    &raquo;</a>
                
                            </div>
                            <br>
                        </div>
                    </div>
                    {%endif%}
                    {%endfor%}
                </div>

            </div>
        </div>
   
        
                              
{% endblock %}

auctions/templates/auctions/index_view.html
{% extends "auctions/layout.html" %}

{%block body%}

{% include "auctions/index-view-swiper.html" %}
<div class="container margin-bottom">

    <div class="row featurette">
        <div class="col-lg-12">
            <i class="fa fa-toggle-on"  aria-hidden="true">{{product.active}}</i>

            <div>
                <h2>{{product.title}} </h2><br>
            </div>

            <div>
                Description
                <p>{{product.description}}</p>
            </div>

            <div>
                Price
                <p class="col-6 ml-2">${{product.price}}</p>
            </div>

            <div>
                Seller
                <p class="col-6 ml-2">{{product.seller}}</p>
            </div>

        </div>

        <div>
            <a href="{% url 'addWatchlist' auction_id=product.id %}" class="btn btn-light col-2 pr-2">Add to
                Watchlist</a>
        </div>
    </div>

    <hr class="featurette-divider">


</div>

{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>

        <script src="https://use.fontawesome.com/4e6d04bfb5.js"></script>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
        <title>Auctions</title>
        <link rel="shortcut icon" type="image/ico" href="{% static 'favico.ico' %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
            integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'auctions/background.css' %}">
        <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/carousel/">
        <link rel="stylesheet" type="text/css" href="{% static 'products.css' %}">
        
    </head>

    <body>
        <header class="p-3 bg-dark text-white">
            <div class="container">
                <div div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                    <div>
                        {% if user.is_authenticated %}
                            Welcome <br><strong>{{ user.username }}</strong>.
                        {% else %}
                            Not signed in.
                        {% endif %}
                    </div>
                    
                    <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0 dropdown show">
                        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                            <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
                          </a>
                        
                            <a class="nav-link px-2 text-white" href="{% url 'index' %}">Home</a>
                        
            
                        {% if user.is_authenticated %}
                    
                                
                                    <a class="nav-link px-2 text-white dropdown-toggle" href="" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                                        aria-haspopup="true" aria-expanded="false">
                                        Category
                                    </a>
                                
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                        {% for category in categories%}
                                        <a class="dropdown-item" value="{{category.id}}" href="{% url 'categoryList' category_id=category.id %}">{{category}}</a>
                                        {%endfor%}
                                    </div>
                         
                            
                                <a class="nav-link px-2 text-white" href="{% url 'watchlist' %}">Watchlist</a>

                                <a class="nav-link px-2 text-white" href="{% url 'createListing' %}">Upload</a>
                            
                    </ul>


                                <div class="text-end">
                                    <a  style="text-align: right;" class="btn btn-warning" href="{% url 'logout' %}">Log Out</a>

                                </div>
                            
                            {% else %}
        
                            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
        
                                <input type="search" class="form-control form-control-dark" placeholder="Search...">
        
                            </form>
        
                            <div >
                                <a class="btn btn-outline-light me-2" href="{% url 'login' %}">Log In for David</a>
                           
                                <a class="btn btn-warning" href="{% url 'register' %}">Register for David</a>
                            </div>
                           
                           
                        {% endif %}
            

                </div>

            </div>
        </header>
    

        <hr>
        {% block body %}
        
        {% endblock %}

     
    </body>
</html>

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">{% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">{% csrf_token %}
        
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}

auctions/templates/auctions/slider.html

{% load static %}
<head>
  
  <link rel="stylesheet" href="{% static 'auctions/swiper-bundle.min.css' %}">
</head>
<body>

  <!-- Swiper -->
  <div class="swiper-container" style="margin-bottom: 100px;">
    <div class="swiper-wrapper">
        {% for auction in auctions %}
            <div class="swiper-slide"><img  src="{{auction.image.url}}" alt="" width = 100% ></div>
        {%endfor%}
    </div>
    <!-- Add Pagination -->
    <div class="swiper-pagination"></div>
    <!-- Add Arrows -->
    <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div>
  </div>

  <!-- Swiper JS -->
  <script src="{% static '/auctions/scripts/swiper-bundle.js' %}"></script>

  <!-- Initialize Swiper -->
  <script>
    var swiper = new Swiper('.swiper-container', {
      slidesPerView: 1,
      spaceBetween: 30,
      loop: true,
      autoplay: {
        delay: 2500,
        disableOnInteraction: false,
      },
      pagination: {
        el: '.swiper-pagination',
        clickable: true,
      },
      navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
      },
    });
  </script>
</body>


auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

{% block body %}

{%if message%}

<div class="alert alert-success" role="alert">

    {{message}}

</div>

{% endif %}

<div class="container margin-bottom">
    <h3 style="text-align:center;">Watchlist</h3>
  {% for product in product_watchlist %}
      <div class="row featurette">
          <div class="col-md-7">
              <li style="text-align: right;">{{product.product_id.active}}</li>
              <div >
                  <h2>{{product.product_id.title}} </h2><br>
              </div>
              
              <div>
                      Description
                  <li>{{product.product_id.description}}</li>
              </div>
              <div>
                  Seller
                  <li>{{product.product_id.seller}}</li>
              </div>
              
              
            </div>
            <div class="col-md-5">
                <img src="{{product.product_id.image.url}}" alt="" width="500" height="500"> 
            </div>
            <a class="btn btn-light col-2 pr-2" href="{% url 'remove_watchlist' auction_id=product.product_id.id %}">Remove From Watchlist</a>
      </div>

      <hr class="featurette-divider">

  {%endfor%}

</div>



{% endblock %}